#!/bin/bash
/space/www/admin/bin/inc-version.sh ./views/head.php


#template css
cd css/theme1/
#$SASS sass/style.scss:style.css
$SASS sass/global.scss:global.css
$SASS tei-sass/tei.scss:tei.css


#cd tei
#$SASS tei.scss:tei.css


#companion wordpress css
#cd /space/psc/www/html/wp-content/themes/psc1/css/
#$SASS style.scss:style.css
