<?xml version="1.0" encoding="UTF-8"?>
		<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs" version="2.0">
			<xsl:variable name="umbrellas"><topic name="Abolition"></topic>
<topic name="Abolitionists"></topic>
<topic name="Adams-Onis Treaty"><u>International Relations</u><u>Territorial Expansionism</u></topic>
<topic name="African American"></topic>
<topic name="African Americans"><u>African American</u></topic>
<topic name="Aging"><u>Stages of Life</u></topic>
<topic name="Agriculture"><u>Industry</u><u>Science</u></topic>
<topic name="Aladdin Oven"><u>Science</u></topic>
<topic name="Alien and Sedition Acts"><u>Law</u></topic>
<topic name="American Colonization Society"></topic>
<topic name="American Party"><u>Political Groups</u></topic>
<topic name="American Revolution"></topic>
<topic name="American System"><u>Economics</u><u>Government</u></topic>
<topic name="American Temperance Society"></topic>
<topic name="Amistad"><u>Slavery and Enslaved Persons</u><u>International Relations</u><u>Law</u></topic>
<topic name="Anglo-American Commercial Treaty of 1795"></topic>
<topic name="Anglo-American Definitive Peace Treaty"><u>International Relations</u><u>Wars and Revolutions</u></topic>
<topic name="Anglo-American Treaty of 1818"></topic>
<topic name="Anti-Federalists"><u>Political Groups</u></topic>
<topic name="Anti-Masonic Party"><u>Political Groups</u></topic>
<topic name="Anti-Slavery Movements"><u>Slavery and Enslaved Persons</u><u>Reform</u></topic>
<topic name="Anti-Slavery Petitions"><u>Slavery and Enslaved Persons</u><u>Reform</u></topic>
<topic name="Army"></topic>
<topic name="Art"></topic>
<topic name="Articles of Confederation"><u>Government</u><u>Law</u></topic>
<topic name="Arts, Visual and Performing"><u>Art</u><u>Culture</u></topic>
<topic name="Asylum Movement"><u>Reform</u></topic>
<topic name="Attorney General"><u>Government</u><u>Law</u></topic>
<topic name="Authorship"><u>Publications and Press</u></topic>
<topic name="Bank Failures"><u>Economics</u></topic>
<topic name="Bank of the United States"><u>Economics</u><u>Government</u></topic>
<topic name="Bank Veto"><u>Economics</u></topic>
<topic name="Bank War"><u>Government</u></topic>
<topic name="Banks, Pet"><u>Economics</u></topic>
<topic name="Barbary Pirates"></topic>
<topic name="Barbary Wars"><u>Wars and Revolutions</u></topic>
<topic name="Benevolence"></topic>
<topic name="Bible"><u>Religion</u><u>Literature</u></topic>
<topic name="Bill of Rights"></topic>
<topic name="Blockades"><u>Economics</u><u>International Relations</u></topic>
<topic name="Boylston Professor of Rhetoric and Oratory"><u>Education</u><u>Work</u></topic>
<topic name="Bread"><u>Food and Drink</u></topic>
<topic name="Cabinet"><u>Government</u></topic>
<topic name="Canals"><u>Travel and Transportation</u></topic>
<topic name="Caribbean"><u>Identity</u><u>Travel and Transportation</u></topic>
<topic name="Catholicism"><u>Religion</u><u>Identity</u></topic>
<topic name="Caucus System"><u>Politics</u></topic>
<topic name="Censure"><u>Politics</u></topic>
<topic name="Character"><u>Identity</u></topic>
<topic name="Charity"><u>Work</u><u>Society</u></topic>
<topic name="Chesapeake Affair"><u>International Relations</u></topic>
<topic name="Childbirth"><u>Health</u><u>Stages of Life</u></topic>
<topic name="Childcare"></topic>
<topic name="Childhood"><u>Stages of Life</u></topic>
<topic name="Church of Jesus Christ of Latter-day Saints"><u>Religion</u></topic>
<topic name="Circuit Court"><u>Law</u></topic>
<topic name="Civil War"><u>Wars and Revolutions</u></topic>
<topic name="Class"><u>Society</u></topic>
<topic name="Clothing"><u>Society</u></topic>
<topic name="Colonization Movements"><u>Migration</u><u>Reform</u></topic>
<topic name="Comity"><u>Government</u></topic>
<topic name="Commerce"><u>Economics</u></topic>
<topic name="Congress"><u>Government</u></topic>
<topic name="Constitutional Interpretation"><u>Law</u></topic>
<topic name="Continental Congress"><u>Government</u></topic>
<topic name="Continental System"><u>Economics</u><u>Wars and Revolutions</u></topic>
<topic name="Contracts"><u>Economics</u></topic>
<topic name="Convention of 1800"><u>International Relations</u></topic>
<topic name="Convention of 1818"><u>International Relations</u><u>Territorial Expansionism</u></topic>
<topic name="Cooking"><u>Food and Drink</u></topic>
<topic name="Corporations"><u>Economics</u></topic>
<topic name="Corrupt Bargain"><u>Politics</u></topic>
<topic name="Corruption"><u>Politics</u></topic>
<topic name="Court Life and Society, European"><u>Culture</u><u>International Relations</u><u>Society</u></topic>
<topic name="Courtship"><u>Personal Relationships</u><u>Stages of Life</u></topic>
<topic name="Courtship and Marriage of JQA and LCA"><u>Personal Relationships</u><u>Stages of Life</u></topic>
<topic name="Crime"><u>Society</u></topic>
<topic name="Culture"></topic>
<topic name="Currency"><u>Economics</u></topic>
<topic name="Death"><u>Stages of Life</u></topic>
<topic name="Delegation"><u>Politics</u></topic>
<topic name="Democratic Party"><u>Political Groups</u></topic>
<topic name="Democratic-Republican Party"><u>Political Groups</u></topic>
<topic name="Dietaries"><u>Food and Drink</u></topic>
<topic name="Diplomacy"><u>International Relations</u></topic>
<topic name="Disasters"><u>Nature</u><u>Society</u></topic>
<topic name="Disinterestedness"><u>Identity</u></topic>
<topic name="Domestic Animals"></topic>
<topic name="Domestic Life and Duties"><u>Work</u><u>Gender</u><u>Society</u></topic>
<topic name="Dred Scott v. Sandford"><u>Politics</u><u>Slavery and Enslaved Persons</u><u>Law</u></topic>
<topic name="Dueling"><u>Society</u></topic>
<topic name="Economic Theory"><u>Economics</u></topic>
<topic name="Economics"><u>Economics</u></topic>
<topic name="Education"><u>Education</u></topic>
<topic name="Educational Reform"></topic>
<topic name="Elections"><u>Elections</u></topic>
<topic name="Elections, Congressional"><u>Elections</u></topic>
<topic name="Elections, Presidential"><u>Elections</u></topic>
<topic name="Elections, Presidential 1796"><u>Elections</u></topic>
<topic name="Elections, Presidential 1800"><u>Elections</u></topic>
<topic name="Elections, Presidential 1808"><u>Elections</u></topic>
<topic name="Elections, Presidential 1812"><u>Elections</u></topic>
<topic name="Elections, Presidential 1816"><u>Elections</u></topic>
<topic name="Elections, Presidential 1820"><u>Elections</u></topic>
<topic name="Elections, Presidential 1824"><u>Elections</u></topic>
<topic name="Elections, Presidential 1828"><u>Elections</u></topic>
<topic name="Elections, Presidential 1832"><u>Elections</u></topic>
<topic name="Elections, Presidential 1836"><u>Elections</u></topic>
<topic name="Elections, Presidential 1840"><u>Elections</u></topic>
<topic name="Elections, Presidential 1844"><u>Elections</u></topic>
<topic name="Elections, Presidential 1848"><u>Elections</u></topic>
<topic name="Elections, State and Local"><u>Elections</u></topic>
<topic name="Emancipation"><u>Slavery and Enslaved Persons</u><u>Law</u></topic>
<topic name="Embargo"><u>Economics</u><u>International Relations</u><u>Law</u></topic>
<topic name="Embargo Act of 1807"></topic>
<topic name="Employees"><u>Work</u></topic>
<topic name="Equality"></topic>
<topic name="Era of Good Feelings"><u>Politics</u><u>Government</u></topic>
<topic name="Essex Junto"><u>Political Groups</u></topic>
<topic name="European Alliances"><u>International Relations</u></topic>
<topic name="Exiles"><u>Politics</u><u>Migration</u></topic>
<topic name="Family"></topic>
<topic name="Family Finances (Adams Family)"><u>Economics</u><u>Family</u></topic>
<topic name="Family Finances (Sedgwick Family)"><u>Economics</u><u>Family</u></topic>
<topic name="Family Finances (Taney Family)"><u>Economics</u><u>Family</u></topic>
<topic name="Family Relations (Adams Family)"><u>Family</u><u>Personal Relationships</u></topic>
<topic name="Family Relations (Sedgwick Family)"><u>Family</u><u>Personal Relationships</u></topic>
<topic name="Family Relations (Taney Family)"><u>Family</u><u>Personal Relationships</u></topic>
<topic name="Family Residences (Adams Family)"><u>Family</u></topic>
<topic name="Family Residences (Sedgwick Family)"><u>Family</u></topic>
<topic name="Family Residences (Taney Family)"><u>Family</u></topic>
<topic name="Fatherhood"><u>Personal Relationships</u><u>Stages of Life</u></topic>
<topic name="Federal Courts"></topic>
<topic name="Federalism"><u>Government</u></topic>
<topic name="Federalist Papers"><u>Politics</u><u>Publications and Press</u></topic>
<topic name="Federalist Party"><u>Political Groups</u></topic>
<topic name="Financial Panics"><u>Economics</u></topic>
<topic name="Florida Annexation"><u>Territorial Expansionism</u></topic>
<topic name="Food and Drink"><u>Food and Drink</u></topic>
<topic name="Force Bill of 1833"></topic>
<topic name="Foreign Relations"><u>International Relations</u></topic>
<topic name="French Revolution"><u>Wars and Revolutions</u></topic>
<topic name="Friendship"><u>Personal Relationships</u></topic>
<topic name="Fugitive Slave Laws"><u>Slavery and Enslaved Persons</u><u>Law</u></topic>
<topic name="Gag Rule"><u>Politics</u><u>Slavery and Enslaved Persons</u></topic>
<topic name="Gardens"><u>Work</u><u>Culture</u></topic>
<topic name="Gender"></topic>
<topic name="Gender Roles"><u>Gender</u></topic>
<topic name="Gifts"><u>Personal Relationships</u><u>Society</u></topic>
<topic name="Government"></topic>
<topic name="Habeas Corpus"><u>Law</u></topic>
<topic name="Haitian Revolution"><u>Wars and Revolutions</u></topic>
<topic name="Hartford Convention"><u>Political Groups</u></topic>
<topic name="Health"></topic>
<topic name="Health and Illness"><u>Health</u></topic>
<topic name="Holidays and Celebrations"><u>Society</u></topic>
<topic name="Home Economics"><u>Education</u><u>Science</u><u>Society</u></topic>
<topic name="House of Representatives"><u>Government</u></topic>
<topic name="Housewares and Furnishings"><u>Society</u></topic>
<topic name="Identity"></topic>
<topic name="Immigration"><u>Migration</u></topic>
<topic name="Impressment"><u>International Relations</u></topic>
<topic name="Independent Treasury"><u>Economics</u></topic>
<topic name="Indian Removal"><u>Indigenous Peoples</u><u>Law</u></topic>
<topic name="Indians"></topic>
<topic name="Indigenous Peoples"></topic>
<topic name="Industrialization"><u>Economics</u><u>Industry</u></topic>
<topic name="Industry"></topic>
<topic name="Internal Improvements"><u>Economics</u><u>Travel and Transportation</u></topic>
<topic name="International Relations"></topic>
<topic name="Jacksonian Democracy"><u>Political Groups</u></topic>
<topic name="Jay Treaty"><u>International Relations</u></topic>
<topic name="Judaism"><u>Religion</u><u>Identity</u></topic>
<topic name="Judicial Philosophy"><u>Law</u></topic>
<topic name="Juries"></topic>
<topic name="Know-Nothings"></topic>
<topic name="Laboratory"><u>Science</u></topic>
<topic name="Latin American Wars of Independence"><u>Wars and Revolutions</u></topic>
<topic name="Law"></topic>
<topic name="Legal Issues"><u>Law</u></topic>
<topic name="Leisure Activities"><u>Culture</u></topic>
<topic name="Literature"></topic>
<topic name="Literature and History"><u>Literature</u></topic>
<topic name="Louisiana Purchase"><u>Territorial Expansionism</u></topic>
<topic name="Lowell System"></topic>
<topic name="Loyalists"><u>Political Groups</u><u>Wars and Revolutions</u></topic>
<topic name="Manifest Destiny"></topic>
<topic name="Manners"><u>Culture</u><u>Society</u></topic>
<topic name="Marriage"><u>Personal Relationships</u><u>Stages of Life</u></topic>
<topic name="Maryland Judiciary"><u>Government</u></topic>
<topic name="Maryland Legislature"><u>Government</u></topic>
<topic name="Menus"><u>Food and Drink</u></topic>
<topic name="Merchants"><u>Economics</u></topic>
<topic name="Mexican Independence"></topic>
<topic name="Mexican War"><u>Wars and Revolutions</u></topic>
<topic name="Mexican War of Independence"><u>Wars and Revolutions</u></topic>
<topic name="Mexican-American War (1846-1848)"></topic>
<topic name="Middle Passage"></topic>
<topic name="Migration"></topic>
<topic name="Missouri Compromise"><u>Politics</u><u>Slavery and Enslaved Persons</u><u>Territorial Expansionism</u></topic>
<topic name="Monroe Doctrine"><u>International Relations</u></topic>
<topic name="Morality and Ethics"><u>Philosophy</u><u>Society</u></topic>
<topic name="Mormons"></topic>
<topic name="Motherhood"><u>Personal Relationships</u><u>Stages of Life</u></topic>
<topic name="Naples Table Fellowship"></topic>
<topic name="Napoleonic Wars"><u>Wars and Revolutions</u></topic>
<topic name="National Identity"><u>Identity</u></topic>
<topic name="National Nominating Conventions"><u>Politics</u></topic>
<topic name="National Republican Party"><u>Political Groups</u></topic>
<topic name="National Road"></topic>
<topic name="Native Americans"><u>Indigenous Peoples</u></topic>
<topic name="Nativists"></topic>
<topic name="Natural World"><u>Nature</u></topic>
<topic name="Nature"></topic>
<topic name="Navy"></topic>
<topic name="New England Kitchen"><u>Food and Drink</u></topic>
<topic name="Northwest Ordinance"><u>Law</u><u>Territorial Expansionism</u></topic>
<topic name="Nullifcation Crisis"></topic>
<topic name="Nullification"><u>Politics</u><u>Law</u><u>Philosophy</u></topic>
<topic name="Nutrition"><u>Society</u></topic>
<topic name="Orders in Council"><u>Government</u><u>Law</u></topic>
<topic name="Oregon Country"><u>Territorial Expansionism</u></topic>
<topic name="Orphanages"></topic>
<topic name="Panic of 1819"><u>Economics</u></topic>
<topic name="Panic of 1837"><u>Economics</u></topic>
<topic name="Patents"><u>Science</u></topic>
<topic name="Patronage"><u>Government</u></topic>
<topic name="Personal Habits"><u>Identity</u></topic>
<topic name="Personal Relationships"></topic>
<topic name="Pet Banks"></topic>
<topic name="Philosophy"></topic>
<topic name="Pinckney's Treaty"><u>International Relations</u></topic>
<topic name="Piracy"></topic>
<topic name="Political Groups"></topic>
<topic name="Political Partisanship"><u>Politics</u></topic>
<topic name="Political Philosophy"><u>Politics</u></topic>
<topic name="Political Upheavals"></topic>
<topic name="Political Violence"><u>Politics</u></topic>
<topic name="Politics"><u>Politics</u></topic>
<topic name="Popular Will"></topic>
<topic name="Postal Service"><u>Government</u></topic>
<topic name="Pregnancy"><u>Health</u><u>Stages of Life</u></topic>
<topic name="President"><u>Government</u></topic>
<topic name="Press"><u>Publications and Press</u></topic>
<topic name="Prison Reform"><u>Reform</u></topic>
<topic name="Privacy"><u>Society</u></topic>
<topic name="Private Practice"><u>Law</u></topic>
<topic name="Private Spheres"></topic>
<topic name="Privateering"><u>Economics</u><u>International Relations</u></topic>
<topic name="Pro-Slavery Movements"><u>Slavery and Enslaved Persons</u></topic>
<topic name="Progressive Women"><u>Reform</u></topic>
<topic name="Prussian-American Treaty of Amity and Commerce"><u>International Relations</u></topic>
<topic name="Public Debt"></topic>
<topic name="Public Disturbances"></topic>
<topic name="Public Health"><u>Society</u></topic>
<topic name="Public Lands"><u>Politics</u><u>Migration</u></topic>
<topic name="Public Memory"></topic>
<topic name="Public Service"><u>Government</u><u>Society</u></topic>
<topic name="Publication"><u>Publications and Press</u></topic>
<topic name="Publications and Press"></topic>
<topic name="Quasi-War"><u>Wars and Revolutions</u></topic>
<topic name="Race and Ethnicity"><u>Identity</u></topic>
<topic name="Railroads"><u>Travel and Transportation</u></topic>
<topic name="Ratification"></topic>
<topic name="Recreation"><u>Health</u><u>Society</u></topic>
<topic name="Reform"></topic>
<topic name="Reform Movements"><u>Reform</u></topic>
<topic name="Regional Identity"><u>Identity</u></topic>
<topic name="Religion"><u>Religion</u></topic>
<topic name="Removal of Deposits"><u>Economics</u></topic>
<topic name="Roads"><u>Travel and Transportation</u></topic>
<topic name="Romanticism"><u>Culture</u><u>Philosophy</u></topic>
<topic name="Rule of Law"><u>Law</u></topic>
<topic name="Science"></topic>
<topic name="Science and Technology"><u>Science</u></topic>
<topic name="Secession"><u>Politics</u></topic>
<topic name="Second Great Awakening"><u>Religion</u></topic>
<topic name="Sectionalism"><u>Politics</u><u>Identity</u><u>Philosophy</u></topic>
<topic name="Self-reflection"><u>Identity</u></topic>
<topic name="Seminole Wars"><u>Indigenous Peoples</u><u>Wars and Revolutions</u></topic>
<topic name="Senate"><u>Government</u></topic>
<topic name="Separate Spheres"></topic>
<topic name="Separation of Powers"><u>Government</u></topic>
<topic name="Shays's Rebellion"><u>Political Upheavals</u></topic>
<topic name="Shopping and Material Exchange"><u>Economics</u><u>Culture</u></topic>
<topic name="Singlehood"><u>Identity</u></topic>
<topic name="Slave Trade"><u>Economics</u><u>Slavery and Enslaved Persons</u></topic>
<topic name="Slavery and Enslaved Persons"><u>Slavery and Enslaved Persons</u></topic>
<topic name="Smithsonian Institution"><u>Culture</u><u>Science</u></topic>
<topic name="Social Life and Networks"><u>Personal Relationships</u></topic>
<topic name="Society"></topic>
<topic name="South American Wars of Independence"></topic>
<topic name="South, The"><u>Politics</u><u>Identity</u></topic>
<topic name="Specie Circular"><u>Economics</u></topic>
<topic name="Speeches"><u>Literature</u><u>Publications and Press</u></topic>
<topic name="Spoils System"><u>Politics</u><u>Work</u><u>Government</u></topic>
<topic name="Stages of Life"></topic>
<topic name="States Rights"><u>Politics</u><u>Government</u><u>Philosophy</u></topic>
<topic name="Statutory Interpretation"></topic>
<topic name="Steam Power"><u>Industry</u><u>Science</u><u>Travel and Transportation</u></topic>
<topic name="Suffrage"><u>Reform</u></topic>
<topic name="Supreme Court"><u>Law</u></topic>
<topic name="Supreme Court Nominations"><u>Politics</u></topic>
<topic name="Tariff of 1816"><u>Economics</u></topic>
<topic name="Tariff of 1828"><u>Economics</u></topic>
<topic name="Tariff of 1832"><u>Economics</u></topic>
<topic name="Tariff of 1833"><u>Economics</u></topic>
<topic name="Tariff of Abominations"></topic>
<topic name="Tariffs"><u>Economics</u></topic>
<topic name="Taxing Power"><u>Government</u></topic>
<topic name="Teaching"><u>Education</u></topic>
<topic name="Telegraph"><u>Science</u></topic>
<topic name="Temperance Movement"><u>Reform</u></topic>
<topic name="Territorial Expansion"><u>Territorial Expansionism</u></topic>
<topic name="Territorial Expansionism"></topic>
<topic name="Territories"><u>Government</u></topic>
<topic name="Texas Annexation"><u>Slavery and Enslaved Persons</u><u>Territorial Expansionism</u></topic>
<topic name="Texas Revolution and Independence"><u>Wars and Revolutions</u></topic>
<topic name="Textile Industry"><u>Industry</u><u>Science</u></topic>
<topic name="Trail of Tears"></topic>
<topic name="Transcendentalism"><u>Culture</u><u>Philosophy</u><u>Reform</u></topic>
<topic name="Transcontinental Treaty"></topic>
<topic name="Transfer Drafts"><u>Economics</u></topic>
<topic name="Translation"><u>Culture</u><u>Literature</u></topic>
<topic name="Transportation"><u>Travel and Transportation</u></topic>
<topic name="Travel and Touring, International"><u>Travel and Transportation</u></topic>
<topic name="Travel and Touring, US"><u>Travel and Transportation</u></topic>
<topic name="Travel and Transportation"></topic>
<topic name="Treasury Department"><u>Government</u></topic>
<topic name="Treaties"><u>International Relations</u></topic>
<topic name="Treaty of Ghent"><u>International Relations</u></topic>
<topic name="Treaty of Mortefontaine"></topic>
<topic name="Treaty of Paris"></topic>
<topic name="Treaty of San Lorenzo El Real"></topic>
<topic name="Underground Railroad"><u>Slavery and Enslaved Persons</u><u>African American</u></topic>
<topic name="Union"><u>Political Groups</u></topic>
<topic name="Unitarianism"><u>Religion</u></topic>
<topic name="Urban Life"><u>Society</u></topic>
<topic name="US Constitution"><u>Government</u><u>Law</u></topic>
<topic name="Utopian Communities"><u>Culture</u><u>Philosophy</u><u>Reform</u></topic>
<topic name="Veterans"><u>Politics</u><u>Wars and Revolutions</u></topic>
<topic name="Veto Power"><u>Government</u></topic>
<topic name="Village Life"><u>Society</u></topic>
<topic name="War Department"><u>Government</u></topic>
<topic name="War of 1812"><u>Wars and Revolutions</u></topic>
<topic name="Wars and Revolutions"></topic>
<topic name="Webster-Ashburton Treaty"><u>International Relations</u></topic>
<topic name="West Indies"></topic>
<topic name="West, The"><u>Politics</u><u>Identity</u><u>Territorial Expansionism</u></topic>
<topic name="Westward Exploration and Expansion"></topic>
<topic name="Westward Migration"></topic>
<topic name="Whig Party"><u>Political Groups</u></topic>
<topic name="Widowhood"><u>Identity</u><u>Stages of Life</u></topic>
<topic name="Wilmot Proviso"><u>Slavery and Enslaved Persons</u><u>Territorial Expansionism</u></topic>
<topic name="Women's Education"><u>Education</u><u>Gender</u></topic>
<topic name="Women's Rights"><u>Gender</u><u>Reform</u></topic>
<topic name="Wool Combustion"><u>Science</u></topic>
<topic name="Work"><u>Work</u></topic>
<topic name="XYZ Affair"><u>International Relations</u></topic>
</xsl:variable></xsl:stylesheet>